server:
  port:8080
#数据库连接
spring:
  datasource:
    url: jdbc:mysql://10.0.18.13:3306/bigdata?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: HWW123_yu@qing